### ISSUE TITLE
Invalid URL errror when generating sitemap.

### ISSUE THREAD

**Issue by brpaz** [Quasibit/eleventy-plugin-sitemap#31]
Hello.

I was trying the plugin, but when I run build, it fails with the following error and have no idea if I am doing something wrong.

```
> (./src/sitemap.njk)
  EleventyShortcodeError: Error with Nunjucks shortcode `sitemap`

`Template render error` was thrown
> Invalid URL: /

`Template render error` was thrown:
    TypeError [ERR_INVALID_URL]: Invalid URL: /
        at onParseError (internal/url.js:259:9)
        at new URL (internal/url.js:335:5)
        at Object.normalizeURL (/home/bruno/Code/Playground/eleventy-template/node_modules/sitemap/dist/lib/utils.js:274:15)
        at SitemapStream._transform (/home/bruno/Code/Playground/eleventy-template/node_modules/sitemap/dist/lib/sitemap-stream.js:77:65)
        at SitemapStream.Transform._read (internal/streams/transform.js:205:10)
        at SitemapStream.Transform._write (internal/streams/transform.js:193:12)
        at writeOrBuffer (internal/streams/writable.js:358:12)
        at SitemapStream.Writable.write (internal/streams/writable.js:303:10)
        at sitemap (/home/bruno/Code/Playground/eleventy-template/node_modules/@quasibit/eleventy-plugin-sitemap/src/sitemap.js:21:12)
        at Object.getSitemap (/home/bruno/Code/Playground/eleventy-template/node_modules/@quasibit/eleventy-plugin-sitemap/.eleventy.js:19:12)
Copied 1 file / Wrote 0 files in 0.17 seconds (v0.12.1)
```

I just have a simple site with an index and about pages.

Using Eleventy 0.12.1.

**Comment by nunof07** [comment]
Hi @brpaz . Can you please verify if the `hostname` is set in the plugin options? Like this:

```js
  eleventyConfig.addPlugin(sitemap, {
    sitemap: {
      hostname: "https://example.com",
    },
  });
```

**Comment by brpaz** [comment]
Hi. I had the config but I was missing the "http://" part on the URL. It works now. Thanks.
