### ISSUE TITLE
This plugin causes a build fail

### ISSUE THREAD

**Issue by peterlobster** [Quasibit/eleventy-plugin-sitemap#47]
I've tried adding this to two different projects, and even a template, and I always get the same build fail... I'm using the provided template.

```
# npm start

> start
> npx @11ty/eleventy --quiet --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Having trouble rendering njk template ./src/sitemap.njk

`TemplateContentRenderError` was thrown
[11ty] > (./src/sitemap.njk) [Line 2, Column 4]
  unknown block tag: sitemap

`Template render error` was thrown:
[11ty]     Template render error: (./src/sitemap.njk) [Line 2, Column 4]
      unknown block tag: sitemap
        at Object._prettifyError (/mnt/site/node_modules/nunjucks/src/lib.js:36:11)
        at Template.init (/mnt/site/node_modules/nunjucks/src/environment.js:511:19)
        at Template.Obj (/mnt/site/node_modules/nunjucks/src/object.js:62:15)
        at new Template (/mnt/site/node_modules/nunjucks/src/environment.js:478:18)
        at Nunjucks.compile (/mnt/site/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:479:14)
        at Html.compile (/mnt/site/node_modules/@11ty/eleventy/src/Engines/Html.js:16:28)
        at TemplateRender.getCompiledTemplate (/mnt/site/node_modules/@11ty/eleventy/src/TemplateRender.js:238:26)
        at Template.compile (/mnt/site/node_modules/@11ty/eleventy/src/TemplateContent.js:294:42)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Template._render (/mnt/site/node_modules/@11ty/eleventy/src/TemplateContent.js:388:16)
[11ty] Wrote 0 files in 0.14 seconds (v1.0.0)

```

**Comment by nunof07** [comment]
Hi @peterlobster . Did you add the plugin in `.eleventy.js`?

**Comment by peterlobster** [comment]
Yes, and I installed it too.

**Comment by nunof07** [comment]
Please provide a repo I can look at.
